version: "2.0"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database    
    links:
      - database
    ports:
      - "80:80"
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: features
    expose:
      - 5432
     
